### ISSUE TITLE
Error Tag Rename

### ISSUE THREAD

**Issue by foomep** [kalvn/Shaarli-Material#24]
i write the old an the new tag in the form and go to Rename Tag.
The site reload and at the ?do=changetag site i get a 404 Not found error.
with the original theme it works fine. i use the fork from https://github.com/shaarli/Shaarli

**Comment by kalvn** [comment]
The [last commit](https://github.com/kalvn/Shaarli-Material/commit/d2596e8bce7c3c4b52d86b4e3122cd9eed8bf6ba) fixes this issue. You can [download the current master branch](https://github.com/kalvn/Shaarli-Material/archive/master.zip) to get it.

This bug is due to a little weirdness in Shaarli (see this issue https://github.com/shaarli/Shaarli/issues/428 ).

**Comment by foomep** [comment]
it works fine. thx :+1:
