### ISSUE TITLE
Issue with blockquotes and preview images

### ISSUE THREAD

**Issue by NerosTie** [kalvn/Shaarli-Material#31]
There is an issue with blockquotes and preview images (a jpg or coming from youtube).

![shaarli_material_2](https://cloud.githubusercontent.com/assets/4572452/13068427/9749d65c-d47b-11e5-82c4-dc2ceb97717f.png)

https://jeekajoo.eu/links/?hrF4xA

![shaarli_material_3](https://cloud.githubusercontent.com/assets/4572452/13068452/c5314f00-d47b-11e5-9907-7edfcf810608.png)

https://jeekajoo.eu/links/?-WBucA

**Comment by kalvn** [comment]
Indeed. Thank you for the feedback, I'll fix this quickly.

**Comment by kalvn** [comment]
This one is more tricky than I thought.

The problem here is that the image stands within a floating container. As you may know, floats create room so the text spread around them. But the borders or background still behave as if the floating element wasn't there, which cause the bug you reported. It's well explained [here](https://www.sitepoint.com/community/t/div-border-overlaps-float/1883).

So I could have add a margin to the whole content of the block when there's an image but currently, Shaarli is built in a way that makes impossible to detect whether there's an image or not. So I cannot do a CSS rule like this `.thumb + .link-description{ padding-left: 150px;} .link-description{ padding: 15px;}`. In fact the `.thumb` container is always present since the image content is populated inside it, if the content exists.

So for now, the only workaround I found is to move the image on the right. The last master branch includes the fix (through this commit 39e5fd9cc48b3bb8215669b2428ceeb74dacddeb).

I'll try to investigate deeper with Shaarli devs.

**Comment by ArthurHoaro** [comment]
You probably can work this around doing something like this:

```
{$thumb=$value.url|thumbnail}
{if="$thumb!='not a thumbnail'"}
  <div class="thumb">{$thumb}</div>
{/if}
```

**Comment by kalvn** [comment]
Great idea thanks, I didn't think about putting the result of a filter in a variable.
I'll have a try.

**Comment by kalvn** [comment]
I tried but apparently it does not work.
The line is compiled in:

```php
<?php $thumb=$this->var['thumb']=$value1["url"]|thumbnail;?>
```

which obviously isn't correct.

**Comment by ArthurHoaro** [comment]
You're right. This works:

```
{$thumb=thumbnail($value.url)}
{if="$thumb==false"}yay{/if}
```

**Comment by kalvn** [comment]
Great thanks! The last commit (f12c05e6a897a95c0cbb800448ab539adb86225e) fixes definitely the issue.

**Comment by NerosTie** [comment]
Thanks! :+1:
