### ISSUE TITLE
QR Codes are displayed even when related plugin is disabled

### ISSUE THREAD

**Issue by aurmil** [kalvn/Shaarli-Material#37]
hello

why force QR Code presence in linklist.html in your theme?
should be responsibility of the plugin only
is there a technical reason?

I don't want this plugin to be enabled so I would like not to display QR codes, without editing your code (custom edits will be lost at every update)

thanks
regards

**Comment by kalvn** [comment]
It's due to the first versions of Shaarli where the QR code button was present by default with no possibilities to remove it.

The plugin system now allows to make it more dynamic but there is only one placeholder for links (a place where plugins can inject content) which I placed on the top right corner. Due to design choices, this plugin does not work well with this theme. That's why I decided to keep the historical QR code control.

But you're right on the fact that not everybody wants this QR code functionality. I'll think about a way of handling your issue, maybe with a theme parameter, even though I don't want to add too many parameters.

In the meantime, you can remove the HTML corresponding to the QR code. You shouldn't be bothered as updates are quite rare and not mandatory.

**Comment by aurmil** [comment]
OK, thanks for answering

so my next question is: why did you choose to group $plugins_header.buttons_toolbar and $plugins_header.fields_toolbar in the same place?
I see that in base template, $plugins_header.buttons_toolbar is in header and $plugins_header.fields_toolbar is in linklist
I'm absolutely new to Shaarly, but this fact makes me think plugins can inject code in 2 differents places

regards

**Comment by kalvn** [comment]
Simply because both buttons and fields are controls, and I want to keep controls in the toolbar. And as the toolbar is almost out of space, I had to group them in the same hidden block.
It may change in the future depending on plugins which will make use of those placeholders but for now it allows to keep things tidy and have sort of a dedicated place for plugins.

**Comment by nicolasdanelon** [comment]
What about use `position: absolute ` I mean use the default placeholder and move the icon to the top and right position of the box (:

**Comment by kalvn** [comment]
Well, it's not a matter of positioning the placeholder itself, in fact I could put it wherever I want. But for the bottom right space is dedicated for specific controls with specific icons and I cannot allow plugins to add content there as it will include inconsistencies in the design. That's why I put the placeholder in the upper right corner, but I still have no control on it.

What I could do is intercepting the event of the QR code plugin icon and make it work well with Shaarli Material but the design still looks weird with the default icon.

**Comment by kalvn** [comment]
I added a new option to disable the default QR Code control.

```php
$GLOBALS['config']['MATERIAL_NO_QRCODE'] = true;
```
