### ISSUE TITLE
Tags are way too big!

### ISSUE THREAD

**Issue by NerosTie** [kalvn/Shaarli-Material#45]
Because of this commit: https://github.com/kalvn/Shaarli-Material/commit/e97a26bd04439c53edbdda5e715eb1c0dfc9d177, my tags are really big!

![screenshot_20160426_063839](https://cloud.githubusercontent.com/assets/4572452/14807113/ac794e4c-0b79-11e6-80e0-050e75ebb940.png)

If I change `em` -> `pt`, it's ok.

**Comment by kalvn** [comment]
Yes it's due to a recent change of Shaarli (https://github.com/shaarli/Shaarli/commit/a1703c44c63852cf54d979a50921dc3a09508a82). Did you upgraded your Shaarli installation to the last version available in the master branch?

Usually, the master branch of Shaarli Material is meant to work with the master branch of Shaarli. And in the same manner, Shaarli Material releases are meant to work properly with Shaarli releases (with the same version number). So if you want to avoid any bug like this in the future, you can try to stay in this scheme.

**Comment by NerosTie** [comment]
Ho! I didn't know about that! So, this is a false issue and I can close it. 
Thank you!
