### ISSUE TITLE
Compatibility with emojione plugin and the ASCII Smiley option

### ISSUE THREAD

**Issue by NerosTie** [kalvn/Shaarli-Material#47]
I wrote a plugin for emojis support with Shaarli. Everything works well but not one particular option with the Material theme.

https://github.com/NerosTie/emojione/issues/5

Material has a strange behavior with ASCII emojis like `:)` at the beginning of a line (that means they are not converted) if the markdown plugin is activated. And they are not converted in tag area too.

This issue do not exists with the default theme and I can't find where is the difference in your theme...

Could you help me? :pray:

**Comment by kalvn** [comment]
I'll have a look (even though I have no idea how emojione works).

**Comment by kalvn** [comment]
It looks like it's due to this bug: https://github.com/Ranks/emojione/issues/54
If, when looking at the HTML code, the emoji is right next to an HTML tag, it'll fail. So you can try for example, even on the default Shaarli theme, if you write this: 

```
test :)
another line
```

the equivalent HTML code will be

```html
test :)<br>
another line
```

It'll fail as the emoji will be just next to the `<br>` tag which makes the new line.

And therefore, it often fails in Shaarli Material because you target `.link-tag` which are `<span>` containing a `<a>`, meaning that the first and last tags will be ignored (because just next to the opening or closing tag of `a`).

Same thing for the `.link-description` when enabling markdown because the markdown plugin created an extra div around the `<p>` containing the description. It means that an emoji at the beginning of the description or at the end will be ignored. You will even have more issues if you use markdown syntax which will generate HTML tags, if those are located next to your emojis.

So to conclude, I would suggest to wait and see if they solve the issue. But as it was opened 1 year ago, it may never be fixed. Otherwise, it could be possible to fix the issue in their library by yourself.

**Comment by NerosTie** [comment]
With the default theme, this line:
```
test :)
another line
```
works if markdown is activated but it fails if markdown is deactivated and this the opposite behavior in the material theme...

> So to conclude, I would suggest to wait and see if they solve the issue. But as it was opened 1 year ago, it may never be fixed. Otherwise, it could be possible to fix the issue in their library by yourself.

Thanks for the all explanation!  

Well, this bug seems to be related to to ASCII and emojione, not the Material theme as I thought. Using ASCII is always risky in that case and this an option in a plugin, so I will not try to fix it by myself (maybe the emojione team will find a solution in their library).
