### ISSUE TITLE
save shaarlink when pressing 'enter' in tag field (while editing a shaarlink)

### ISSUE THREAD

**Issue by jeekajoo** [kalvn/Shaarli-Material#5]
Hi,
again thanks for this wonderful theme.

How to reproduce:

1) edit a shaarlink
2) place cursor in tag field
3) press enter
4) you are asked if you want to delete the shaarlink.

4) expected behaviour: just save the shaarlink

Is this something that is do-able on your side? or is this something in shaarli community code.

Thanks
J.

**Comment by kalvn** [comment]
It was due to the order of the buttons in the HTML code so it's only due to the theme.
I reordered them so that the Save button is the first and consequently the default one.
Commit: https://github.com/kalvn/Shaarli-Material/commit/b00be5ca18322efd5c70ffcc8183225aa2ce480a

The current master version implements this change.

Thanks for opening this issue (and the others) :)

**Comment by jeekajoo** [comment]
you rock :+1: 
thanks
