### ISSUE TITLE
Broken on last Version.

### ISSUE THREAD

**Issue by farfeduc** [kalvn/Shaarli-Material#50]
As the config has been moved to data/config.json.php , there is no more config.php.

Resulting in a lot of errors like this on almost every pages: 

`Notice: Undefined index: config in /var/www/shaarli/tmp/linklist.aeadca0864f49f08401fb0f97c162898.rtpl.php on line 64`

How can I fix that ?

Thank you in advance !

**Comment by kalvn** [comment]
That's perfectly normal because Shaarli configuration system has been completely revamped.

Therefore, I had to update the theme in order to make it work with the last development version of Shaarli. It has been done through the following commit d3790320ca0f8eb1ac3086f553197f079f2a4c1d

So to fix this, you should download and install the last master branch version of Shaarli Material.

Just a general comment about this situation: each time Shaarli is updated with important changes such as this time, it requires some time for me to adapt the theme to take those changes into consideration. Therefore, if you want to avoid such issues in the future, you should wait a little before updating Shaarli and then update both Shaarli and Shaarli Material at the same time.

**Comment by farfeduc** [comment]
Ok ! Thank you very much ! :+1:  :smile:
