### ISSUE TITLE
Support of the tags advanced plugin

### ISSUE THREAD

**Issue by iGormilhit** [kalvn/Shaarli-Material#57]
It would be nice that, *one day*, the theme supports the [tags advanced](https://framagit.org/framasoft/myframa/tree/master/shaarli/plugins/tags_advanced) plugin. I think that yet, this plugin is only supported by the theme of [MyFrama](https://my.framasoft.org/) instance.

**Comment by kalvn** [comment]
As far as I see, this plugin uses the old way to access the local configuration (`$GLOBALS['config']` instead of `$config->get`). Therefore, there is no way to make it work on a recent installation of Shaarli. Once this is fixed, it should work out of the box. There may only be a bit of work to consider in terms of design but that should be it.

**Comment by kalvn** [comment]
I close this issue as it is related to external developments.
